ci:
  autoupdate_schedule: quarterly
exclude: '.*.weldx'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
  # ----- Python formatting -----
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
    # Run ruff linter.
    - id: ruff
      args:
      - --quiet
      - --fix
  # Run ruff formatter.
    - id: ruff-format
