name: weldx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - setuptools_scm
  - pip
  # Notebook + Plotting
  - jupyterlab=2
  - ipykernel
  - matplotlib=3.3.2
  - ipympl=0.5.8
  - nodejs
  - asdf=2.8.1
  - pip:
      - git+https://github.com/BAMWelDX/weldx.git@c240216fbc0d4695c7ad2d96b14b488f0163a112
