name: weldx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - setuptools_scm
  - pip
  # Notebook + Plotting
  - jupyterlab=2
  - ipykernel
  - matplotlib=3.3.2
  - ipympl=0.5.8
  - nodejs
  - k3d=2.9.3
  - asdf=2.8.1
  - pip:
    - weldx==0.4.0
