name: weldx
channels:
  - conda-forge
dependencies:
  - python=3.11
  - setuptools_scm
  - pip
  # Notebook + Plotting
  - ipykernel
  - matplotlib=3.7.2
  - ipympl=0.9.3
  - k3d=2.16.1
  # pinned asdf & weldx versions
  - asdf=2.15.*
  - weldx=0.6.9
  - weldx_widgets=0.2.5
  # sphinx build
  - sphinx=7.2.6
  - myst-nb=1.0.0
  - furo=2024.5.6

