name: pytest
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 8 * * 0'

jobs:
  pytest:
    name: pytest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        py: ['3.8']
        weldx_version:
          - 'weldx==0.5.0'
          - 'weldx'
          - 'git+https://github.com/BAMWelDX/weldx.git'
    env:
      WELDX_VERSION: ${{ matrix.weldx_version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/pytest.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: pip installs
        run: |
          pip install wheel
          pip install asdf==2.8.2 $WELDX_VERSION pytest nbval ipympl

      - name: run pytest on notebook
        run: |
          pytest --color=yes --nbval-lax --current-env iiw2021_CXII_fabry_cagtay_01.ipynb
